name: Node.js Package
# 监测图床分支，2020年10月后github新建仓库默认分支改为main，记得更改
on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
      - name: 发布npm包
        if: env.NPM_TOKEN && env.NPM_NAME
        run: |
          n latest
          npm install -g npm
          npm install fs-extra
          node index.js
          npm config set 
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_NAME: ${{ secrets.NPM_NAME }}
