name: 自动部署

on:
  push:
    branches:
      - main #2020年10月后github新建仓库默认分支改为main，注意更改

  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 检查分支
      uses: actions/checkout@v2
      with:
        ref: main #2020年10月后github新建仓库默认分支改为main，注意更改

    - name: 安装 Node
      uses: actions/setup-node@v1
      with:
        node-version: "16.x" 

    - name: 发布npm包
      if: env.NPM_TOKEN && env.NPM_NAME
      run: |
        node index.js
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_NAME: ${{ secrets.NPM_NAME }}